const ActionType = {
  LOAD_MOVIES: `LOAD_MOVIES`,
  LOAD_SPECIAL_MOVIE: `LOAD_SPECIAL_MOVIE`,
  LOAD_GENRES: `LOAD_GENRES`,
  LOAD_REVIEWS: `LOAD_REVIEWS`,
  LOAD_MY_LIST: `LOAD_MY_LIST`,
  SET_GENRE_FILTER: `SET_GENRE_FILTER`,
  RESET_GENRE_FILTER: `RESET_GENRE_FILTER`,
  AUTHORIZE: `AUTHORIZE`,
  DEAUTHORIZE: `DEAUTHORIZE`,
  SHOW_NOTIFICATION: `SHOW_NOTIFICATION`,
  HIDE_NOTIFICATION: `HIDE_NOTIFICATION`,
  CHANGE_MOVIE_STATUS: `CHANGE_MOVIE_STATUS`,
  START_FETCHING: `START_FETCHING`,
  END_FETCHING: `END_FETCHING`
};

export default ActionType;
